### ISSUE TITLE
Making Link URL fields not automatically open in new tab

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-undergraduate-welcome#20]
Hi @teddybradford - On the [Exploring Providence page](https://congratulations.risd.edu/moving-here/exploring-providence/) the Relevant resources and Neighborhoods links:
<img width="1424" alt="screen shot 2018-03-16 at 11 03 18 am" src="https://user-images.githubusercontent.com/14020234/37536820-10915efc-2922-11e8-988f-428b45ee1b33.png">

 open in new tabs, but they link to pages on this site, so I'm looking to have them stay in the same tab.

Can you make this field: 
<img width="452" alt="screen shot 2018-03-16 at 11 03 30 am" src="https://user-images.githubusercontent.com/14020234/37536848-2702312a-2922-11e8-898b-c6224514d0fa.png">

In the Universal - Providence General Info items:

<img width="1429" alt="screen shot 2018-03-16 at 10 23 25 am" src="https://user-images.githubusercontent.com/14020234/37536898-49e62c00-2922-11e8-8689-c8f51168c61c.png">

not set to open in a new tab. Thanks so much!

**Comment by mmarol** [comment]
@teddybradford the URL field in webhook is really annoying because it doesn't allow for relative URLs. I think I have it set up so that relative URLs will have a `target=self` added and absolute URLs will have a `target=_blank` added.

Changing this field to a *Single line text field* would in my mind be the better change. @cmiller02 this would require the links to be re-entered, but it looks like there are just 3 instances so that shouldn't be too much of a problem.

**Comment by teddybradford** [comment]
@cmiller02 I changed the field to be a single text line rather than URL, so relative URLs should be allowed now. I went through and re-added the URLs. This change affected the "Exploring Providence" items and the "Inside RISD" items. It looks like the build queue is backed up, so I don't know when the changes will propagate to the site.

**Comment by mmarol** [comment]
They would be the `Link URL` fields for the 3 General Info items. The URLs would have to be added back in as relative URLs, not absolute ones.

**Comment by cmiller02** [comment]
All looks good in the CMS and seems to be working perfectly on the site, so I'm going to close this out. Thanks very much @teddybradford and @mmarol!
