### ISSUE TITLE
Redirects not working

### ISSUE THREAD

**Issue by mmarol** [risd/risd-undergraduate-welcome#9]
Hey I'm not sure if I just didn't set it up right, but it looks like the URL redirects are not working. Carrie added a couple to the CMS, but it doesn't seem like it did anything.

**Comment by rubillionaire** [comment]
Ahh yeah I see whats up.

I just did a local build of the site and see that there is a page at `/next-steps/next-steps-to-enroll/index.html` & `/next-steps/pre-arrival-checklist/index.html`

When the build process publishes redirects, the first thing it does is check to see if there is already a template in that location. It is seeing that there is, and consequently not writing the redirect template. I was thinking it would be good to preserve any pages that were already built. Since any page can include any content, I figured this filtering could occur in the template.

Couple of ways to go about this.

I could update the server to give the redirects the ability to be published over whatever template might already exist. 

Or the template could be updated to reflect the redirect that is intended to occur at the published page. That would mean an if statement to catch those particular pages, and publish redirects instead of those pages.

In laying out those options, I do think it would make more sense for the redirects to trump the templates. They are an additional layer of control, and jumping into a template to solve that problem is far more invasive.

Let me know what you think, @mmarol.

**Comment by mmarol** [comment]
I'm also into the redirect trumping templates. That way if there's a conflict in some way, we could trace it back to the redirect list, and it wouldn't be just me or you who could fix it.

**Comment by rubillionaire** [comment]
@mmarol as I am making this change, I am noticing one other potential problem with solving the redirect issue in the current URL Redirects panel. This space doesn't know about the different deploy buckets. Publishing a redirect here will apply the redirect to any of the domains that are configured for the site. The rule that says to redirect from `/next-steps/next-steps-to-enroll/ => /next-steps/important-dates/` will take for both `risd-undergraduate-welcome.risd.systems` & `congratulations.risd.edu`.

One relatively simple way to solve this would be to be able to namespace the redirects with their domain. Publishing a redirect for:
`risd-undergraduate-welcome.risd.systems/next-steps/next-steps-to-enroll/ => /next-steps/important-dates/`
would be different than publishing a redirect for
`congratulations.risd.edu/next-steps/next-steps-to-enroll/ => /next-steps/important-dates/`

Which would be different than not including the domain in the redirect URL, which would be publish the redirect to all domains.

Does that seem appropriate?
Is the issue I'm citing one that is of concern for this particular redirect?

**Comment by mmarol** [comment]
For this particular case, the site is already in phase 2 so having the relative paths building redirects for both .systems and .edu is fine. For future/other sites however, separating the development and production redirects would be useful, so using the full domain name makes sense.

**Comment by rubillionaire** [comment]
Since that is the case, we reverted the items to drafts so they are no longer publishing. Since they aren't publishing, the redirects are written.

The redirects not writing in these cases is only useful for preventing redirects being published to domains where the templates are not already publishing a page at that location. This level of control as to which redirect gets pushed to domain should be a function of the URL redirects pane. I made a new issue for that here https://github.com/risd/edu/issues/653

**Comment by room421** [comment]
Quick question on this before we close. Everything above sound great, but I'm wondering about "vanity" URLs. We have existing redirects like risd.edu/sfs which we use for print. Currently this one goes to an existing page (currently http://risd.edu/admissions/student-financial-services/ on ektron and we would want it to go to https://edu.risd.systems/student-financial-services/ for June 19th). Is there a solution?

**Comment by rubillionaire** [comment]
Certainly, @room421. We can have multiple redirects. We can set up the vanity redirect from `/sfs` to `/student-financial-services/`, and then the legacy redirect from `/admissions/student-financial-services/` to `/student-financial-services/`. These can work for both `edu.risd.systems` and `risd.edu`, since they will be the same at launch.

Any new redirects that start off as `edu.risd.systems` specific we can implement with the completion of risd/edu#653. Then when they are ready for `risd.edu` we can remove the domain specification from the redirect and it will publish as a redirect on `risd.edu`.

Let me know if you have any other redirect questions or feel free to close the issue.

**Comment by room421** [comment]
Great. Thanks. I have a working list of new and existing redirects to be created so please let me know via the other ticket when we're ready to start adding them.
